#ifndef DEFAULTSETTINGS_H_INCLUDED
#define DEFAULTSETTINGS_H_INCLUDED

#include "SFML/System.hpp"

extern const sf::Vector2f DEFAULT_SCREEN_RESOLUTION;
extern const unsigned int DEFAULT_TEXT_CHARACTER_SIZE;

#endif // DEFAULTSETTINGS_H_INCLUDED
